name: Update Epr on schedule
# on: workflow_dispatch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - name: Mkdir
        run: mkdir ch

      - name: Fetch Epr resources
        run: wget http://vi.sisi.am/epr -O ch/epr

      - name: Update Epr resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: ch/epr
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
