name: Update Nyam-P on schedule
# on: workflow_dispatch
on:
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '30 */1 * * *'
jobs:
  resources:
    name: Update Nyam-P resources
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Nyam-P resources
        run: wget http://llpp.xyz/ur/sisi.js -O nyam-p.js

      - name: Update Nyam-P resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: nyam-p.js
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
